#
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

### Configuration for Docs Agent ###

### PaLM environment
#
# api_endpoint:    The PaLM API endpoint used by Docs Agent.
#
# embedding_model: The PaLM embedding model used to generate embeddings.
#
api_endpoint: "generativelanguage.googleapis.com"
embedding_model: "models/embedding-gecko-001"


### Docs Agent environment
#
# product_name:    The name of your product to appears on the chatbot UI.
#
# output_path:     The directory where plain text files will be stored
#                  after documentation source files are processed by
#                  the `markdown-to-plain-text.py` script.
#                  Use a relative path to Doc Agent' home directory.
#
# vector_db_dir:   The directory where dataset collections for the Chroma
#                  vector database are stored.
#
# collection_name: The name used to identify a dataset collection by
#                  the Chroma vector database.
#
# log_level:       The verbosity level of logs printed on the terminal
#                  by the chatbot app: NORMAL or VERBOSE
#
product_name: "My product"
output_path: "data/plain_docs"
vector_db_dir: "vector_stores/chroma"
collection_name: "docs_collection"
log_level: "NORMAL"


### Documentation sources
#
# List your documentation sources under the `input` field:
#
# path (Required):         The directory where the source Markdown files
#                          are stored.
#
# url_prefix (Required):   The prefix used to create URLs for the source
#                          files. Even if URLs don't exist for the source,
#                          you still need to provide a mock string.
#
# exclude_path (Optional): The sub-directory to be excluded from the `path`
#                          directory when processing source files.
#
input:
  - path: "data/example/markdown-src-01"
    url_prefix: "https://example.com/markdown-src-01"
  - path: "data/example/markdown-src-02"
    url_prefix: "https://example.com/makrdown-src-02"
    exclude_path: "/reference/changelogs/"


### Docs Agent prompts
#
# condition_text:      The condition added at the top of each prompt to
#                      language models.
#
# fact_check_question: The additional condition used in promopts when asking
#                      language models to "fact check" their own responses.
#
# model_error_message: The error message returned to the user when language
#                      models are unable to provide responses.
#
condition_text: "You are a helpful chatbot answering questions from users.
Read the context below first and answer the user's question at the end.
In your answer, provide a summary in three or five sentences. (BUT DO NOT USE
ANY INFORMATION YOU KNOW ABOUT THE WORLD.)"

fact_check_question: "Can you compare the text below to the information
provided in this prompt above and write a short message that warns the readers
about which part of the text they should consider fact-checking? (Please keep
your response concise, focus on only one important item, but DO NOT USE BOLD
TEXT IN YOUR RESPONSE.)"

model_error_message: "PaLM is not able to answer this question at the moment.
Rephrase the question and try asking again."

